name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repsository
        uses: actions/checkout@v2

      - name: Display build environment
        run: printenv

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.13' # The Go version to download (if necessary) and use.

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            /usr/local/kubebuilder/bin
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}


      - name: Install kubebuilder
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run : |
          os=$(go env GOOS)
          arch=$(go env GOARCH)

          curl -L https://go.kubebuilder.io/dl/2.3.1/${os}/${arch} | tar -xz -C /tmp/

          sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
          export PATH=$PATH:/usr/local/kubebuilder/bin

      - name: Run tests
        # if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          make test
