name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repsository
        uses: actions/checkout@v2

      - name: Display build environment
        run: printenv

      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.13' # The Go version to download (if necessary) and use.
      - run: go version

      # - name: Cache dependencies
      #   id: cache-dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cache/pipenv
      #       ~/.local/share/virtualenvs
      #     key: os-${{ runner.os }}-env-${{ matrix.python-version }}-${{ hashFiles('**/Pipfile.lock') }}-${{ github.ref }}

      - name: Run tests
        # if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          make test
